# fly.toml app configuration file generated for whatsappbot-main on 2024-12-24T16:09:03-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'whatsappbot-main'
primary_region = 'scl'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
